# SPDX-License-Identifier: GPL-2.0-or-later
#
# Copyright The freemyipod team (freemyipod.org)
#

obj-y += s5l87xx.o

obj-$(CONFIG_S5L8702) += reset.o
obj-$(CONFIG_S5L8730) += reset.o

obj-$(CONFIG_S5L8701) += s5l8701.o
obj-$(CONFIG_S5L8702) += s5l8702.o
obj-$(CONFIG_S5L8730) += s5l8730.o
obj-$(CONFIG_S5L8740) += s5l8740.o
