# SPDX-License-Identifier: GPL-2.0-or-later
#
# Copyright (C) 2026 The freemyipod team (freemyipod.org)
#

obj-y += s5l87xx.o
obj-y += s5l87xx-clk.o

obj-$(CONFIG_S5L8701) += s5l8701.o
obj-$(CONFIG_S5L8701) += s5l8701-otg-phy.o
obj-$(CONFIG_S5L8701) += s5l8701-timer.o

obj-$(CONFIG_S5L8702) += reset.o
obj-$(CONFIG_S5L8702) += s5l8702.o
obj-$(CONFIG_S5L8702) += s5l8702-lcdcon.o
obj-$(CONFIG_S5L8702) += s5l8702-otg-phy.o
obj-$(CONFIG_S5L8702) += s5l87xx-timer.o

obj-$(CONFIG_S5L8720) += reset.o
obj-$(CONFIG_S5L8720) += s5l8720.o
obj-$(CONFIG_S5L8720) += s5l87xx-otg-phy.o
obj-$(CONFIG_S5L8720) += s5l87xx-timer.o

obj-$(CONFIG_S5L8723) += reset.o
obj-$(CONFIG_S5L8723) += s5l8723.o
obj-$(CONFIG_S5L8723) += s5l87xx-otg-phy.o
obj-$(CONFIG_S5L8723) += s5l87xx-timer.o

obj-$(CONFIG_S5L8730) += reset.o
obj-$(CONFIG_S5L8730) += s5l8730.o
#obj-$(CONFIG_S5L8730) += s5l87xx-buscon.o
obj-$(CONFIG_S5L8730) += s5l8730-lcdcon.o
obj-$(CONFIG_S5L8730) += s5l87xx-otg-phy.o
obj-$(CONFIG_S5L8730) += s5l87xx-timer.o

obj-$(CONFIG_S5L8740) += s5l8740.o
obj-$(CONFIG_S5L8740) += s5l87xx-otg-phy.o
obj-$(CONFIG_S5L8740) += s5l87xx-timer.o
